// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhiskeyTracker.Web.Data;

#nullable disable

namespace WhiskeyTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114191153_AddBottleToNote")]
    partial class AddBottleToNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhiskeyTracker.Web.Data.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BottlingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("PurchaseLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WhiskeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WhiskeyId");

                    b.ToTable("Bottles");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.TastingNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BottleId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("TastingSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("WhiskeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BottleId");

                    b.HasIndex("TastingSessionId");

                    b.HasIndex("WhiskeyId");

                    b.ToTable("TastingNotes");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.TastingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TastingSessions");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.Whiskey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ABV")
                        .HasColumnType("double precision");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("CaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Distillery")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("Whiskies");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.Bottle", b =>
                {
                    b.HasOne("WhiskeyTracker.Web.Data.Whiskey", "Whiskey")
                        .WithMany("Bottles")
                        .HasForeignKey("WhiskeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Whiskey");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.TastingNote", b =>
                {
                    b.HasOne("WhiskeyTracker.Web.Data.Bottle", "Bottle")
                        .WithMany("TastingNotes")
                        .HasForeignKey("BottleId");

                    b.HasOne("WhiskeyTracker.Web.Data.TastingSession", "TastingSession")
                        .WithMany("Notes")
                        .HasForeignKey("TastingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhiskeyTracker.Web.Data.Whiskey", "Whiskey")
                        .WithMany("TastingNotes")
                        .HasForeignKey("WhiskeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bottle");

                    b.Navigation("TastingSession");

                    b.Navigation("Whiskey");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.Bottle", b =>
                {
                    b.Navigation("TastingNotes");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.TastingSession", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("WhiskeyTracker.Web.Data.Whiskey", b =>
                {
                    b.Navigation("Bottles");

                    b.Navigation("TastingNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
